name: JHipster Azure AD Login
on: [push, pull_request]
jobs:
    applications:
        name: JHipster test suite
        runs-on: ${{ matrix.os }}
        timeout-minutes: 40
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                java_version: ['8.x', '11.x']
        env:
            SPRING_OUTPUT_ANSI_ENABLED: NEVER
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java_version }}
            - name: Stop MySQL server
              run: sudo /etc/init.d/mysql stop
            - name: Install node.js packages
              run: npm install
            - name: Package application
              run: ./mvnw -ntp package -Pprod -DskipTests -DskipIT
